name: Build-database

on:
  push:
    branches:
      - '**'
    paths:
      - ./data/
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
# Placeholder
#   build-bmd:
#     #if: github.actor != 'github-actions[bot]'
#     runs-on: ubuntu-20.04
#     environment: build
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v3
#       - name: Download artifacts from previous drug gen
#         uses: actions/download-artifact@v3
#       - name: Pull sample image
#         run: docker pull sgosline/srp-bmd
#       - name: Run bmd python command
#         run: |
#           docker run -v $PWD:/tmp sgosline/srp-bmd
#       - name: List files cwd
#         run: ls -la
   build-samples:
     #if: github.actor != 'github-actions[bot]'
     runs-on: ubuntu-20.04
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v3
       - name: Download artifacts from previous drug gen
         uses: actions/download-artifact@v3
       - name: Pull sample image
         run: docker pull sgosline/srp-samplechem
       - name: Run sample-chem python command
         run: |
           docker run -v $PWD:/tmp sgosline/srp-samplechem 
       - name: List files cwd
         run: ls -la

   build-expo:
     #if: github.actor != 'github-actions[bot]'
     runs-on: ubuntu-20.04
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v3
       - name: Download artifacts from previous drug gen
         uses: actions/download-artifact@v3
       - name: Pull sample image
         run: docker pull sgosline/srp-exposome
       - name: Run sample-chem python command
         run: |
           docker run -v $PWD:/tmp sgosline/srp-exposome
       - name: List files cwd
         run: ls -la 
       - name: Copy files to artifact
         run: |
           mkdir expo-files
           mv *.csv expo-files
       - name: upload artifact
         uses: actions/upload-artifact@v2
         with:
           name: expo-files
           path: expo-files         

   build-expr:
     #if: github.actor != 'github-actions[bot]'
     runs-on: ubuntu-20.04
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v3
       - name: Download artifacts from previous drug gen
         uses: actions/download-artifact@v3
       - name: Pull sample image
         run: docker pull sgosline/srp-zfexp
       - name: Run zfexp python command
         run: |
           docker run -v $PWD:/tmp sgosline/srp-zfexp
       - name: List files cwd
         run: ls -lah
       - name: Copy files to artifact
         run: |
           mkdir expr--files
           mv *csv expr-files
       - name: upload artifact
         uses: actions/upload-artifact@v2
         with:
           name: expr-files
           path: expr-files

   artifact-test:
     needs: [build-samples,build-expo,build-expr]
     runs-on: ubuntu-20.04
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v2
       - name: Download artifacts from expression
         uses: actions/download-artifact@v2
         with:
           name: expr-files
       - name: Downlod artifacts from exposome
         uses: actions/download-artifacts@v2
         with:
           name: expo-files
       - name: List files cwd
         run: ls -lah 
#zipfiles push to figshare

