name: Build-upload-docker
defaults:
  run:
    working-directory: ./
on:
  push:
    branches:
      - '**'
    paths:
      - .github/
      - zfBmd/
      - zfExp/
      - sampleChemMapping/
      - dbSchema/
      - exposome/
  workflow_dispatch:


jobs:
  build-and-push-sample:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push sampleChem
        run: |
          docker build -t sgosline/srp-samplechem:latest -f ./sampleChemMapping/Dockerfile .
	  docker push sgosline/srp-samplechem:latest
         # platforms: linux/amd64,linux/arm64
  build-push-expo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push expo
        run: |
          docker build -t sgosline/srp-exposome:latest -f ./exposome/Dockerfile .
	  docker push sgosline/srp-exposome:latest
  build-push-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push expo
        run: |
          docker build -t sgosline/srp-dbschema:latest -f ./exposome/dbSchema .
	  docker push sgosline/srp-dbschema:latest
  build-push-exp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push expo
        run: |
          docker build -t sgosline/srp-zfexp:latest -f ./zfExp/Dockerfile .
	  docker push sgosline/srp-zfexp:latest
#      - name: Build and push bmd
#        uses: docker/build-push-action@v6
#        with:
#          context: zfBmd
#          push: true
#          tags: sgosline/srp-zfbmd:latest
#          platforms: linux/amd64,linux/arm64       
#      - name: Build and push bmd2Samps
#        uses: docker/build-push-action@v6
#        with:
#          context: old/bmd2Samps
#          push: true
#          tags: sgosline/srp-bmd2samps:v1
#          platforms: linux/amd64,linux/arm64       
#      - name: Build and push version 2 bmd2Samps
#        uses: docker/build-push-action@v6
#        with:
#          context: old/bmd2Samps_v2
#          push: true
#          tags: sgosline/srp-bmd2samps:latest
#          platforms: linux/amd64,linux/arm64
