name: Docker-build
defaults:
  run:
    working-directory: ./
on:
  push:
    branches:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push bmd
        uses: docker/build-push-action@v2
        with:
          context: zfBmd
          push: true
          tags: sgosline/srp-zfbmd:latest
      - name: Build and push bmd2Samps
        uses: docker/build-push-action@v2
        with:
          context: bmd2Samps
          push: true
          tags: sgosline/srp-bmd2samps:latest
      - name: Build and push exposome
        uses: docker/build-push-action@v2
       with:
          context: exposome
          push: true
          tags: sgosline/srp-exposome:latest
      - name: Build and push dbSchema
        uses: docker/build-push-action@v2
        with:
          context: dbSchema
          push: true
          tags: sgosline/srp-dbschema
      #- name: docker pull
      #  run: "docker pull sgosline/srp-analytics"
      #- name: test LPR
      #  run: "docker run -v $PWD:/tmp sgosline/srp-analytics --test-lpr"
      #- name: test morpho
      #  run: "docker run -v $PWD:/tmp sgosline/srp-analytics --test-morpho"
      #- name: build db
      #  run: "docker run -v $PWD:/tmp sgosline/srp-analytics"
      #- name: validate schemas
      #  run: "docker run -v $PWD:/tmp sgosline/srp-analytics --validate"
